### PR TITLE
Rearch

### PR DESCRIPTION
**Pull request by jschueller**
I'm building an installer involving this dependency and I'm facing issues with noarch packages

### CODE REVIEW

**Comment by jschueller** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> I'm building an installer involving this dependency and I'm facing issues with noarch packages

@jschueller what sort of issues? Maybe we can solve them without reverting this.

**Comment by jschueller** [comment]
I'm using constructor, which does not handle noarch packages.

**Comment by ocefpaf** [comment]
> I'm using constructor, which does not handle noarch packages.

So let's revert it back to `noarch` after this, that way you get your workaround to what , IMO is a constructor bug, and we will go back to the optimized CI configuration.

PS: did you open a bug report about this upstream in the `constructor` repo?

**Comment by jschueller** [comment]
It's already in the known limitations in hte README

**Comment by ocefpaf** [comment]
> It's already in the known limitations in hte README

@jschueller I still think it is worth creating an issue. This limitation would cripple conda-forge CIs if we start to re-arch everything for constructor.

**Comment by jschueller** [comment]
see https://github.com/conda/constructor/issues/86

**Comment by ocefpaf** [comment]
Thanks for the xref @jschueller

**Pull request merged**
